import random
from colorama import Fore, Style

# Existing Tips + 100 Additional Tips
TIPS = [
    "💻 Run sqlmap while you are waiting.",
    "📂 Look for simple files that may seem obvious.",
    "🔑 Have you tried admin:admin yet?",
    "🕵️‍♂️ Check for hidden directories using DirBuster.",
    "🤖 Always review robots.txt for hidden paths.",
    "✨ Sometimes the easiest solutions are the best.",
    "🔐 Test default credentials; they might surprise you.",
    "📥 Check the server response headers for hints.",
    "📜 Try fuzzing parameter values for unexpected results.",
    "💬 Look for comments in the page source; they may reveal hints.",
    "📂 Check if the site is vulnerable to directory traversal.",
    "🔍 Have you enumerated all open ports yet?",
    "🔑 Try brute-forcing login pages with common credentials.",
    "🛠️ Use Burp Suite's intruder to test inputs.",
    "🌐 Don't forget to check for subdomains.",
    "🔒 Scan for SSL/TLS vulnerabilities using sslscan.",
    "🌐 Always test HTTP and HTTPS separately.",
    "🔎 Review the page source for hidden or disabled form fields.",
    "🗂️ Use gobuster or dirbuster for brute-forcing paths.",
    "📂 Check for backup files like .bak or .old.",
    "🔍 Enumerate hidden parameters with tools like Arjun.",
    "📦 Scan for default CMS installations like WordPress or Joomla.",
    "🛠️ Review JavaScript files for exposed API keys.",
    "🍪 Test for weak session cookies with predictable values.",
    "🌐 Try manipulating URL parameters to bypass restrictions.",
    "🖥️ Use Nmap scripts to scan for vulnerabilities.",
    "📡 Search for exploits based on software versions.",
    "💾 Check for database dumps left exposed on the server.",
    "📝 Look for writable directories to upload payloads.",
    "📤 Test file uploads for bypassing extensions or MIME types.",
    "🛡️ Check for weak or missing Content Security Policies.",
    "⏳ Try timing attacks to uncover blind SQLi vulnerabilities.",
    "🔍 Check for exposed .git directories.",
    "📧 Enumerate email addresses for potential spear-phishing.",
    "🔒 Always scan for default admin interfaces.",
    "👾 Look for publicly available exploits using Exploit-DB.",
    "🌍 Test for path normalization bypass.",
    "💥 Scan for local file inclusion (LFI) vulnerabilities.",
    "🗝️ Always check weak hashing algorithms like MD5.",
    "📊 Inspect HTTP status codes for hints (e.g., 403, 500).",
    "📑 Look for unintended access via API endpoints.",
    "🔍 Check cookie flags like HttpOnly and Secure.",
    "🛑 Always validate permissions on critical files.",
    "🔐 Don't forget to test password reset flows for abuse.",
    "💡 Enumerate user accounts using error responses.",
    "📜 Use wfuzz or ffuf for parameter fuzzing.",
    "🖥️ Test for weak CORS configurations.",
    "🛡️ Always run a vulnerability scanner like Nessus or OpenVAS.",
    "📲 Check mobile apps for hardcoded credentials.",
    "🔌 Enumerate services using banner grabbing.",
    "📤 Use exiftool to extract metadata from uploaded files.",
    "🔧 Test for misconfigured cloud storage (e.g., S3 buckets).",
    "📝 Look for publicly accessible development/test servers.",
    "📄 Check for exposed environment variables.",
    "🔒 Ensure proper sanitization of user inputs.",
    "🌐 Test for subdomain takeover vulnerabilities.",
    "🔗 Look for Open Redirect vulnerabilities.",
    "🕵️ Test for information disclosure in error messages.",
    "📚 Search for sensitive information in public code repositories.",
    "💻 Run Gobuster with wordlists for specific web servers.",
    "📊 Enumerate network shares using smbclient.",
    "🔗 Test for hardcoded secrets in IoT devices.",
    "🔧 Enumerate HTTP methods allowed (e.g., PUT, DELETE).",
    "🗝️ Always update and patch known vulnerabilities.",
    "🛑 Check for rate limiting or lack thereof.",
    "🔍 Test for misconfigured Content-Type headers.",
    "🖥️ Use testssl.sh to scan SSL/TLS configurations.",
    "📂 Look for temporary files left behind by developers.",
    "🔐 Use Hydra or Medusa for password brute-forcing.",
    "🔑 Test for Kerberoasting vulnerabilities in AD.",
    "🔍 Analyze DNS zones using zone transfers.",
    "🕵️‍♂️ Use dig or nslookup to enumerate DNS records.",
    "👾 Check for outdated software versions.",
    "🔧 Validate error handling for unexpected input.",
    "📦 Enumerate FTP servers for anonymous login.",
    "🔑 Check for hidden paths in web servers (e.g., .well-known).",
    "🛑 Use Nikto to perform a quick web scan.",
    "🚀 Automate recurring tasks with scripts.",
    "📂 Look for old backups of databases (e.g., .sql).",
    "🔒 Verify HTTPS enforcement with HSTS.",
    "📚 Read logs for traces of exploitation attempts.",
    "🌐 Use WhatWeb to fingerprint web servers.",
    "🔍 Test for insecure Direct Object References (IDOR).",
    "🛡️ Review application security headers like CSP and X-Frame-Options.",
    "🔧 Enumerate SMB shares using enum4linux.",
    "📤 Monitor network traffic for unusual patterns.",
    "🔎 Inspect cron jobs for exploitable scripts.",
    "📡 Analyze emails for signs of phishing attacks.",
    "📱 Test mobile apps with tools like MobSF or Frida.",
    "🔍 Run `strings` on binaries to look for hidden information.",
    "🖥️ Check for RCE via unsanitized input in applications.",
    "💡 Test privilege escalation using misconfigured sudoers."
]

# IT/Cybersecurity Jokes
JOKES = [
    "💡 Why do programmers prefer dark mode? Because light attracts bugs.",
    "💚 How do you comfort a JavaScript bug? You console it.",
    "🤝 Why do security analysts never play hide and seek? Because good luck hiding when they’re scanning the whole network.",
    "🌊 What’s a hacker’s favorite season? Phishing season.",
    "🌳 Why do SysAdmins love nature? It has plenty of root access.",
    "🛡️ Why are firewalls like relationships? They block everything suspicious.",
    "🔔 Why was the network administrator calm? He found his ping of serenity.",
    "🐍 Why do hackers love Python? It’s easy to slither through code.",
    "🛠 Why did the rootkit get promoted? It had excellent persistence.",
    "🤖 Why are botnets great party hosts? They know how to network.",
    "🍑 Why did the malware eat fruit? It loves juicy files.",
    "🧵 Why did the ransomware get rich? It always knew how to hold data hostage.",
    "🔧 Why was the exploit feeling unpatched? It didn’t get fixed in time.",
    "🚫 Why did the virus get locked out? It didn’t pass the antivirus scan.",
    "🐞 Why are keyloggers so sneaky? They’re always under your keys.",
    "🛡️ Why did the hacker love math? It’s all about root access.",
    "🤦‍♂️ Why don’t hackers like to play chess? They hate firewalls.",
    "💀 Why was the malware so dramatic? It kept crashing everything.",
    "🍊 What did the phishing email say? ‘Congratulations! You’ve been hacked.’",
    "🛠️ Why did the botnet apply for a job? It’s great at distributed work.",
    "🎓 Why did the student love ransomware? It always encrypted their homework.",
    "🤷‍♂️ Why don’t exploits tell secrets? Because they always get patched.",
    "🔍 Why did the rootkit go unnoticed? It stayed hidden too well.",
    "🐛 Why are worms good at hide and seek? They hide deep inside your files.",
    "🤯 Why did the botnet throw a party? It wanted to infect everyone.",
    "💊 Why was the virus bad at sports? It couldn’t pass the quarantine test.",
    "🌍 Why do hackers love global variables? They spread everywhere.",
    "🚫 Why didn’t the firewall trust the website? It didn’t have a valid certificate.",
    "🛠️ Why do black hats hate locks? They always find a way around them.",
    "🔧 Why did the ransomware cross the road? To encrypt the other side.",
    "🔒 Why was the cryptojacker always busy? It mined its own business.",
    "🛡 Why don’t viruses take naps? They’re always active processes.",
    "💰 Why do scammers love phishing? It always brings in a catch.",
    "🛠 Why did the exploit feel powerful? It always escalated privileges.",
    "🔑 Why do hackers avoid public Wi-Fi? It’s already full of them.",
    "💡 Why do threat actors love passwords? They’re meant to be cracked.",
    "🛠️ Why did the phishing scam fail? The bait was too obvious.",
    "🤖 Why are DDoS attacks rude? They never stop yelling.",
    "🤏 Why do worms love email? It’s their inbox playground.",
    "🔧 Why are keyloggers patient? They know good things come to those who type.",
    "🚫 Why did the firewall fail? It let a worm slip through.",
    "💰 Why are ransomware authors rich? They hold all the keys."
]

COLORS = [Fore.RED, Fore.GREEN, Fore.BLUE, Fore.MAGENTA, Fore.CYAN, Fore.YELLOW, Fore.WHITE]


def get_random_tip_with_color():
    choice = random.choice(TIPS + JOKES)  # Combine TIPS and JOKES
    color = random.choice(COLORS)
    return f"{color}{choice}{Style.RESET_ALL}"